class PortalContent:
    PING = "content://com.droidrun.portal/ping"
    SOCKET_PORT = "content://com.droidrun.portal/socket_port"
    ENABLE_SOCKET_SERVER = "content://com.droidrun.portal/toggle_socket_server"
    ENABLE_WEBSOCKET_SERVER = "content://com.droidrun.portal/toggle_websocket_server"
    AUTH_TOKEN = "content://com.droidrun.portal/auth_token"
    VERSION = "content://com.droidrun.portal/version"
    A11Y_TREE = "content://com.droidrun.portal/a11y_tree"
    A11Y_TREE_FULL = "content://com.droidrun.portal/a11y_tree_full"
    A11Y_TREE_XML = "content://com.droidrun.portal/a11y_tree?format=xml"
    A11Y_TREE_XML_FULL = "content://com.droidrun.portal/a11y_tree_full?format=xml"
    PHONE_STATE = "content://com.droidrun.portal/phone_state"
    STATE = "content://com.droidrun.portal/state"
    STATE_FULL = "content://com.droidrun.portal/state_full"
    PACKAGES = "content://com.droidrun.portal/packages"

    ENABLE_SERVICE = "content://com.hermes.portal.provider/start-service"
    DISABLE_SERVICE = "content://com.hermes.portal.provider/stop-service"


class PortalHTTP:
    PING = "/ping"
    VERSION = "/version"
    WINDOW_STATE = "/window-state"
    STOP_SERVICE = "/service/stop"
    NODES_XML = "/nodes/xml"
    NODES_JSON = "/nodes/json"
    EASY_ZOOM = "/gesture/easy-zoom"
    ZOOM = "/gesture/zoom"
    PINCH = "/gesture/pinch"
    SCROLL = "/gesture/scroll"
    SWIPE = "/gesture/swipe"
    TAP = "/gesture/tap"
    LONG_PRESS = "/gesture/long-press"
    INPUT_TEXT = "/input/text"
    INPUT_CLEAR = "/input/clear"
    SCROLL_SEARCH = "/action/scroll-search"
    SCREENSHOT = "/screenshot"
