from collections.abc import Mapping
from pathlib import Path
from typing import Literal, Protocol
from subprocess import CompletedProcess

from ..models.common import PopenOutput
from ..models.component import Bounds, Point, Size


class DebugBridgeProtocol(Protocol):
    def cmd(
        self,
        command: str,
        timeout: int = 30000,
        cwd: Path | None = None,
        env: Mapping[str, str] | None = None,
    ) -> CompletedProcess: ...

    def shell(
        self,
        command: str,
        timeout: int = 30000,
        cwd: Path | None = None,
        env: Mapping[str, str] | None = None,
    ) -> CompletedProcess: ...

    def clear_logcat(self): ...

    def stop_logcat(self): ...

    def reboot(self, wait_for_boot_completed: bool = True, timeout: int = 60000): ...

    def wait_for_boot_completed(self, timeout: int = 60000) -> bool: ...

    def get_devices(self) -> list[str]: ...

    def screenshot(self, path: Path | None, display_id: str | None = None) -> Path: ...

    def click_back(self): ...

    def click_enter(self): ...

    def click_home(self): ...

    def click_menu(self): ...

    def click_recent_task(self): ...

    def click_power(self): ...

    def get_window_size(self, refresh: bool = False) -> Size: ...

    def tap(self, x: int, y: int, offset_x: int = 0, offset_y: int = 0): ...

    def long_press(
        self, x: int, y: int, offset_x: int = 0, offset_y: int = 0, duration: int = 2000
    ): ...

    def drag_and_drop(self, start: Point, end: Point, duration: int = 1000): ...

    def swipe(
        self,
        start: Point,
        end: Point,
        duration: int = 500,
        repeat: int = 1,
        wait_render: int = 200,
    ): ...

    def swipe_ext(
        self,
        direction: Literal["up", "down", "right", "left"],
        *,
        scale: float = 0.9,
        bounds: Bounds | None = None,
        duration: int = 500,
        repeat: int = 1,
        wait_render: int = 200,
    ): ...

    def get_datetime(self) -> str: ...

    def pull(self, remote_path: str, local_path: Path): ...

    def push(self, remote_path: str, local_path: Path): ...

    def install(self, apk_path: Path): ...

    def uninstall(self, package_name: str): ...

    def start_app(self, package_name: str, activity_name: str | None = None): ...

    def stop_app(self, package_name: str): ...

    def get_app_info(self, package_name: str) -> str: ...

    def get_app_version(self, package_name: str) -> str | None: ...

    def query_content(self, uri: str) -> str: ...

    def insert_content(self, uri: str, values: dict[str, str]): ...
