from typing import Protocol, Any

from ..models.language import Language
from .debug_bridge_protocol import DebugBridgeProtocol
from .driver_protocol import DriverProtocol


class DeviceProtocol(Protocol):
    @property
    def device_model(self) -> Any: ...

    def set_language(self, language: Language): ...

    def set_implicitly_wait(self, timeout: int): ...

    def ping(self) -> bool: ...

    def connect(self): ...

    def disconnect(self): ...

    def reconnect(self): ...

    @property
    def driver(self) -> DriverProtocol: ...

    @property
    def adb(self) -> DebugBridgeProtocol: ...

    @property
    def hdc(self) -> DebugBridgeProtocol: ...

    def media_calcualte(self): ...
