from typing import Protocol
from pathlib import Path
from ..models.selector import Method, Window


class SelectorToPathProtocol(Protocol):
    def get_window(self) -> Window: ...
    def get_syntax(self) -> str: ...
    def get_method(self) -> Method: ...
    def get_threshold(self) -> float: ...
    def get_image(self) -> Path: ...
